name: Deploy React (Vite) to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

      - name: Build Vite App
        run: npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      - name: Clear previous build on VPS (only dist/)
        uses: appleboy/ssh-action@v1
        with:
          host: 16.79.30.150
          username: ubuntu
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            rm -rf /var/webapps/finvise-frontend/dist/*
            mkdir -p /var/webapps/finvise-frontend/dist

      - name: Git pull on server
        uses: appleboy/ssh-action@v1
        with:
          host: 16.79.30.150
          username: ubuntu
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd /var/webapps/finvise-frontend
            git pull origin main

      - name: Sync dist/ to VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key" \
            dist/ ubuntu@16.79.30.150:/var/webapps/finvise-frontend/dist/
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
