name: Deploy React (Vite) to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Git pull on server
        uses: appleboy/ssh-action@v1
        with:
          host: 16.79.30.150
          username: ubuntu
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: |
            cd /var/webapps/finvise-frontend
            git pull origin main
            sudo npm install -y
            sudo npm run build
